services:
  blink-bridge:
    build: .
    container_name: blink-bridge
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config:/config
    environment:
      - MQTT_BROKER=192.168.0.100
      - MQTT_PORT=1883
      - CONFIG_PATH=/config/blink_config.yaml